dependencies:
  - python=3.11
  - pip
  - pip:
    - jupyter==1.0.0
    - pandas==1.0.0
    - scikit-learn==0.22.1
    - numpy==1.18.1
    - matplotlib==3.1.3
    - seaborn==0.10.0


# this is needed for pyenv & conda environment , not for poetry environment that is used in the project